Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\routes.py", line 8, in index
    return render_template("index.html")
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\base.html", line 24, in template
    {% endfor %} {% endif %} {% block content %}{% endblock %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endwith'. The innermost block that needs to be closed is 'with'.
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\routes.py", line 8, in index
    return render_template("index.html")
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\base.html", line 25, in top-level template code
    {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\index.html", line 6, in block 'content'
    run("{{url_for('upload')}}");
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'upload'. Did you mean 'index' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\routes.py", line 8, in index
    return render_template("index.html")
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    return _render(
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\base.html", line 25, in top-level template code
    {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\app\templates\index.html", line 6, in block 'content'
    run("{{url_for('upload')}}");
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'upload'. Did you mean 'index' instead?
Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Philip\Documents\programmieren\python\filessafe\filessafe\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'upload' did not return a valid response. The function either returned None or ended without a return statement.
